spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}



jwt:
  token:
    secret: ${JWT_TOKEN_SECRET}


oauth2:
  kakao:
    info-url: ${KAKAO_INFO_URL}
    base-url: ${KAKAO_BASE_URL}
    client-id: ${KAKAO_CLIENT_ID}
    redirect-uri: ${KAKAO_REDIRECT_URI}


coolsms:
  api:
    key: ${API_KEY}
    secret: ${API_SECRET}
  senderNumber: ${SENDER_NUMBER}
